DROP TABLE ADMIN;

DROP TABLE DRIVER;

DROP TABLE CUSTOMER;

DROP TABLE CONDUCTOR;

DROP TABLE USER;

CREATE TABLE USER (
    USER_ID INT NOT NULL,
    USER_EMAIL VARCHAR2(1024),
    USER_PASS VARCHAR(10)
);

CREATE TABLE ADMIN (
    ADMIN_ID INT NOT NULL,
    USER_ID INT,
    PRIMARY KEY(ADMIN_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE CUSTOMER (
    CUST_ID INT NOT NULL,
    PHONE NUMBER,
    USER_ID INT,
    PRIMARY KEY(CUST_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE DRIVER (
    DRIVER_ID INT NOT NULL,
    PHONE NUMBER,
    USER_ID INT,
    PRIMARY KEY (DRIVER_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE CONDUCTOR (
    CONDUCTOR_ID INT NOT NULL,
    PHONE NUMBER,
    USER_ID INT,
    PRIMARY KEY (DRIVER_ID),
    FOREIGN KEY(USER_ID) REFERENCES USER (USER_ID) ON DELETE CASCADE
);