-- TOTAL PRICE CALCULATE --
-- STOPPAGE --
-- EMAIL OF CUSTOMER --
-- SEAT TYPE --


-- LAB 3

SELECT *   FROM TICKET; 


SELECT NUMBER_PLATE, COST FROM BUS
WHERE COST>=500 AND COST<=1000 ;


-- DISTINCT Cost between 500 to 1000

SELECT DISTINCT(COST) AS distinct_cost, NUMBER_PLATE FROM BUS
WHERE COST>=500 AND COST<=1000 ;

-- LIKE (SUB STRING MATCH)--
-- select start point a bus where start_point contains LA as a sub string (COMILLA)

SELECT START_POINT 
FROM SCHEDULE
WHERE START_POINT LIKE '%LA%';


-- DESC OF COST --
SELECT NUMBER_PLATE, COST FROM BUS
ORDER BY COST DESC;

-- CALCULTE ALL TICKET PRICE BY COUNT 
-- AT FIRST GET TICKET PRICE FROM CO-RESPONDING BUS

-- ///// TO DOOOO // -----------



-- SELECT MAX COST GROPU BY BUS TYPE --
SELECT MAX(COST), BUS_TYPE
FROM BUS
GROUP BY BUS_TYPE;
------------------------------------