-- JOIN --
SELECT T.TICKET_NUMBER, U.USER_NAME
FROM TICKET T , CUSTOMER C, USERS U
WHERE T.CUST_ID = C.CUST_ID AND U.USERS_ID = C.USERS_ID;

-- __QUERY__ : Select bus and route_id where capacity > 40 or capacity less then 40 
SELECT BUS_TYPE, ROUTE_ID
FROM BUS
WHERE  CAPACITY < 40  
UNION
SELECT BUS_TYPE, ROUTE_ID
FROM BUS
WHERE  CAPACITY > 40  ;


SELECT TICKET_NUMBER, USER_NAME
FROM TICKET T CROSS JOIN CUSTOMER C CROSS JOIN USERS U
WHERE T.CUST_ID = C.CUST_ID AND U.USERS_ID = C.USERS_ID;


SELECT TICKET_NUMBER, USER_NAME
FROM TICKET T NATURAL JOIN (CUSTOMER C NATURAL JOIN USERS U);


SELECT  B.NUMBER_PLATE , S.ROUTE_ID
FROM BUS B LEFT OUTER JOIN SCHEDULE S
ON B.ROUTE_ID = S.ROUTE_ID;